encrypt:
  key: ${CONFIG_CLIENT_KEY}
spring:
  application:
    name: kafka-to-elastic-service
  profiles:
    active: kafka_to_elastic,dev
  config:
    import: 'configserver:'
  cloud:
    config:
      name: kafka-to-elastic-service,config-client
      username: spring_cloud_user
      password: "{cipher}b070010b6ea5ff61dd83f4013184f73251e5d16ace7ef627faae5fe7c81f2b90"

log:
  app-name: kafka-to-elastic-service