spring:
  application:
    name: kafka-to-elastic-service
  profiles:
    active: kafka_to_elastic,dev
  config:
    import: 'configserver:'
  cloud:
    config:
      name: kafka-to-elastic-service,config-client
      username: spring_cloud_user
      password: "(cipher)8289224e8c63a064873a230458a40b8201d284d8d4eb0bcb3bea87b14b06d10e"

log:
  app-name: kafka-to-elastic-service