spring:
  application:
    name: kafka-to-elastic-service
  profiles:
    active: kafka_to_elastic,dev
  config:
    import: 'configserver:'
  cloud:
    config:
      name: kafka-to-elastic-service,config-client
      username: spring_cloud_user
      password: "(cipher)6b8ebd86e8a5cbbcb681e18638e3f3d13f7a21087a5d16f2fa8d912839dbfb88"

log:
  app-name: kafka-to-elastic-service