encrypt:
  key: ${CONFIG_CLIENT_KEY}
spring:
  application:
    name: twitter-to-kafka-service
  profiles:
    active: twitter_to_kafka,dev
  config:
    import: 'configserver:'
  cloud:
    config:
      name: twitter-to-kafka-service,config-client
      username: spring_cloud_user
      password: "{cipher}b070010b6ea5ff61dd83f4013184f73251e5d16ace7ef627faae5fe7c81f2b90"

log:
  app-name: twitter-to-kafka-service
