spring:
  application:
    name: twitter-to-kafka-service
  profiles:
    active: twitter_to_kafka,dev
  config:
    import: 'configserver:'
  cloud:
    config:
      name: twitter-to-kafka-service,config-client
      username: spring_cloud_user
      password: "(cipher)8289224e8c63a064873a230458a40b8201d284d8d4eb0bcb3bea87b14b06d10e"
log:
  app-name: twitter-to-kafka-service
