version: '3.7'
services:
  config-service:
    image: ${GROUP_ID}/config:${SERVICE_VERSION:-latest}
    hostname: config-service
    ports:
      - "8888:8888"
    networks:
      - ${GLOBAL_NETWORK:-services}
    volumes:
      - "./docker-logs:/workspace/config-service/logs"
    environment:
      - "JAVA_OPTS=-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005 -Xms128m -Xmx256m"
      - "ENCRYPT_KEY=${CONFIG_CLIENT_KEY}"