server:
  port: 8888

logging:
  level:
    ROOT: INFO
    org.spring.framework.cloud.config: DEBUG
spring:
  application:
    name: configserver
  cloud:
    config:
      server:
        git:
          uri: https://github.com/BerkerIgdir/twitter-kafka-repo
          clone-on-start: true
          username: BerkerIgdir
          password: "{cipher}1aa97a8fb79a3a536a1c1f725d554ee687e5a162bdbf79755822bda794fa337d4838483db09ac10b4cd5ed5744da8f7016686c1e01f5d875eaa3166898a2f312"
          default-label: main
        encrypt:
          enabled: true
      fail-fast: true
  security:
    user:
      name: spring_cloud_user
      password: "{cipher}b070010b6ea5ff61dd83f4013184f73251e5d16ace7ef627faae5fe7c81f2b90"
#        "{cipher}b070010b6ea5ff61dd83f4013184f73251e5d16ace7ef627faae5fe7c81f2b90"
encrypt:
  key: ${CONFIG_CLIENT_KEY}